name: aegisub
#version: 'latest'
adopt-info: aegisub
summary: Aegisub is a free open-source cross-platform subtitle editing program
description: |Aegisub is a free, cross-platform open source tool for creating and modifying subtitles. Aegisub makes it quick and easy to time subtitles to audio, and features many powerful tools for styling them, including a built-in real-time video preview.
  
license: 	3-clause BSD License

base: core16
grade: edge
confinement: strict

apps:
  aegisub:
    command: aegisub  
    environment:
      LC_ALL: C.UTF-8
    plugs:
      - home
      
parts:
  bashtop:
    source: https://github.com/aegisub/aegisub  
    source-type: git
    plugin: make
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed 's/^v//')"
      
    build-packages:
      - bash
      - awk
      - coreutils
      - grep
      - sed
      
    stage-packages:
      - bash
      - awk
      - coreutils
      - grep
      - sed   
      - python3-psutil
      - lm-sensors
      - sysstat
      - curl
